### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Sshahar** [jollygoose/oxygen-cursors-snap#1]
Hey, thanks for the repository. I tried following the instructions in the README.md file and encountered an error when running the following command:
```
$ snap install oxygen-cursors_CURRENT_all.snap --dangerous
error: cannot open "oxygen-cursors_CURRENT_all.snap": open oxygen-cursors_CURRENT_all.snap: no such file or directory
```

**Comment by jollygoose** [comment]
Hello, and apologies missing this comment, and responding so late. The `oxygen-cursors_CURRENT_all.snap` filename is a sort of placeholder, and mostly likely won't exist on the host. It would be swapped for the file generated from the snap build. For example, if after running `snapcraft` the file `oxygen-cursors_0.0.2012-06-kde4.8-2.1ubuntu1_amd64.snap` was created, then the installation would be:

```
snap install oxygen-cursors_0.0.2012-06-kde4.8-2.1ubuntu1_amd64.snap --dangerous 
```

CURRENT was supposed to be a placeholder for the `0.0.2012-06-kde4.8-2.1ubuntu1` portion. Will try to make the README a bit clearer.  I just saw the [snapcraft syntax has changed with core22](https://snapcraft.io/docs/reference-architectures#heading--build-for). core18 which currently in use is no long supported. This also makes for another reason to change the README a bit since the produced filename's pattern.

Will add the change here soon. Think it will mostly be consist of the below changes in the `snapcraft` file:
```
...
base: core22
...
architectures:
 - build-on: [arm64, amd64]
   build-for: [arm64]
 - build-on: [arm64, amd64]
   build-for: [amd64]
...
```
